### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by rozzzly** [of-human-bondage/react-proptypes-intellisense#29]
It'd be cool if you added support for typescript projects that import react components which do not have typings (ie: type defintions beyond `declare module 'some-component';`)

There are a lot of awesome react components out there on npm, but the vast majority are written in JS and do not have type defintions. Many of theme do, however, have proptype definitions which this extension can leverage.

**Comment by tempora-mutantur** [comment]
@rozzzly Hi, thanks for your suggestion, we'll take a look at this.

**Comment by tempora-mutantur** [comment]
Hi @rozzzly .
We haven't find a solution to make this work with JS libraries **without** typings. Most of them have already compiled code where all PropTypes were cut out. For those libs that have PropTypes in compiled code it is very hard to take props because they all use different approaches for compilation and it's hard to cover all of them.
